[package]
name = "rs-md-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.28.1"
eframe = "0.28.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
pulldown-cmark = "0.9"

[profile.release]
lto = true
panic = 'abort'